---
- name: Ensure prereqs installed
  become: true
  register: docker_service
  tags:
    - docker
  dnf:
    update_cache: true
    name:
      - docker
      - python3-pip

- name: Ensure pip packages installed
  become: true
  pip:
    name:
      - docker-compose

- name: Enable docker service
  when: docker_service.changed
  become: true
  tags:
    - docker
  systemd:
    name: docker.service
    enabled: true
    daemon_reload: true
    state: restarted
