---
- when: ansible_distribution|lower == 'ubuntu'
  tags:
    - docker
  include_tasks: ubuntu.yml

- when: ansible_distribution|lower == 'amazon'
  tags:
    - docker
  include_tasks: amazon.yml

- name: Ensure docker group membership
  become: true
  when: docker_add_to_group|bool
  tags:
    - docker
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true

- name: Ensure additional docker group members
  become: true
  loop: "{{ docker_additional_group_members }}"
  tags:
    - docker
  user:
    name: "{{ item }}"
    groups: docker
    append: true

- name: Flush handlers
  meta: flush_handlers
  tags: ['always']
