---
- name: Install apt prerequisites
  become: yes
  apt:
    pkg:
      - docker.io

- name: Install pip3 prerequisites
  become: yes
  pip:
    executable: /usr/bin/pip3
    name:
      - docker

- name: Ensure docker group membership
  become: yes
  when: docker_add_to_group|bool
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
