---
- name: Ensure dns prereqs installed
  become: yes
  notify: Enable docker service
  dnf:
    name:
      - docker
      - pip
    update_cache: yes

- name: Ensure docker-compose installed
  become: yes
  pip:
    name: docker-compose

# - name: Test if docker installed
#   register: docker_stat
#   changed_when: docker_stat.rc == 1
#   failed_when: no
#   tags:
#     - docker
#   command: which docker

# - name: Install docker
#   when: docker_stat.changed
#   notify: Enable docker service
#   become: yes
#   tags:
#     - docker
#   command: yum install -y docker docker-compose
