---
- name: Ensure inbox prereqs removed
  become: yes
  tags:
    - docker
  dnf:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine

- name: Ensure repository
  become: yes
  tags:
    - docker
  ini_file:
    path: /etc/yum.repos.d/docker.repo
    section: repo
    option: baseurl
    value: https://download.docker.com/linux/fedora/docker-ce.repo
    owner: root
    group: root
    mode: "600"

- name: Ensure docker installed
  become: yes
  register: docker_service
  tags:
    - docker
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: yes

- name: Enable docker service
  when: docker_service.changed
  become: yes
  tags:
    - docker
  systemd:
    name: docker.service
    enabled: yes
    daemon_reload: yes
    state: restarted
