---
- name: Ensure apt prerequisites
  notify: Enable docker service
  become: yes
  tags:
    - docker
  apt:
    update_cache: yes
    cache_valid_time: 900
    pkg:
      - ca-certificates
      - curl
      - gnupg
  register: apt_prereq_action
  retries: 100
  until: apt_prereq_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Ensure inbox docker components removed
  notify: Enable docker service
  become: yes
  tags:
    - docker
  apt:
    state: absent
    pkg:
      - docker.io
      - docker.compose
      - docker-doc
      - podman-docker
      - containerd
      - runc
  register: apt_remove_action
  retries: 100
  until: apt_remove_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Check for existing gpg key
  tags:
    - docker
  stat:
    path: /etc/apt/keyrings/docker.gpg
  register: stat_gpg

- when: stat_gpg.stat.exists is not defined or stat_gpg.stat.exists|bool == false
  tags:
    - docker
  block:
    - name: Download armored gpg key
      become: yes
      tags:
        - docker
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        owner: root
        group: root

    - name: Dearmor gpg key
      become: yes
      tags:
        - docker
      shell: gpg --dearmor -o /etc/apt/keyrings/docker.gpg

    - name: Remove armored gpg key
      become: yes
      tags:
        - docker
      file:
        path: /etc/apt/keyrings/docker.asc
        state: absent

- name: Ensure repository
  become: yes
  tags:
    - docker
  apt_repository:
    repo : deb [arch="amd64" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

- name: Ensure docker installed
  notify: Enable docker service
  become: yes
  tags:
    - docker
  apt:
    update_cache: yes
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  register: apt_action
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)
